<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>AllenNeuralDynamics.CuttlefishCamTrigger</Title>
    <Authors></Authors>
    <Copyright>Copyright © 2025 Allen Institute for Neural Dynamics</Copyright>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
    <Description>Bonsai Library containing interfaces for data acquisition and control of AllenNeuralDynamics CuttlefishCamTrigger devices.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageType>Dependency;BonsaiLibrary</PackageType>
    <PackageTags>AllenNeuralDynamics CuttlefishCamTrigger Bonsai Rx</PackageTags>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageOutputPath></PackageOutputPath>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <VersionPrefix>0.1.0-preview03</VersionPrefix>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bonsai.Harp" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\LICENSE" PackagePath="/" />
    <Content Include="..\icon.png" PackagePath="/" />
    <EmbeddedResource Include="..\..\..\..\device.yml" />
  </ItemGroup>

</Project>
